services:

  web:
    image: biocorredor-mr:23072e2f24293cc58f1219d4b58cfac16ea3c23f
    container_name: biocorredor-mr-web
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - proxy-net

  pb:
    image: biocorredor-mr-pb
    container_name: biocorredor-mr-pb
    restart: unless-stopped
    command:
      - /pb/pocketbase
      - serve
      - --http=0.0.0.0:8090
      - --hooksDir=/pb/pb_hooks
      - --dev
    expose:
      - "8090"
    volumes:
      - biocorredor-mr-pb-data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_hooks:/pb/pb_hooks
    networks:
      proxy-net:
        aliases:
          - pb

volumes:
  biocorredor-mr-pb-data:
    external: true
    name: biocorredor-mr-pb-data

networks:
  proxy-net:
    external: true
